from __future__ import annotations

import json
from typing import Any

from analyzers.data_analyzer import (
    build_computed_data_insights,
    build_data_profile,
)
from prompts.data_analysis_prompt import build_data_analysis_prompt


ALLOWED_OPERATIONS = {
    "SUMMARY",
    "AGGREGATE",
    "COMPARE",
    "FILTER",
    "SORT",
    "GROUP",
    "OUTLIER",
    "CORRELATION",
    "TREND",
    "FORECAST",
}

ALLOWED_AGGREGATES = {"SUM", "MEAN", "MEDIAN", "MIN", "MAX", "COUNT", "STD"}
ALLOWED_FILTER_OPERATORS = {"=", "!=", ">", ">=", "<", "<="}
SAFE_LIMIT_MIN = 1
SAFE_LIMIT_MAX = 50


def _clean_json_text(text: str) -> str:
    cleaned = str(text or "").strip()
    cleaned = cleaned.replace("```json", "").replace("```", "").strip()

    if cleaned.startswith("{") and cleaned.endswith("}"):
        return cleaned

    start = cleaned.find("{")
    end = cleaned.rfind("}")

    if start >= 0 and end > start:
        return cleaned[start : end + 1]

    return cleaned


def _as_list(value: Any) -> list[Any]:
    return value if isinstance(value, list) else []


def _safe_number(value: Any) -> float | None:
    try:
        return float(value)
    except (TypeError, ValueError):
        return None


def _fmt_number(value: Any) -> str:
    number = _safe_number(value)
    if number is None:
        return str(value or "")
    if number.is_integer():
        return f"{int(number):,}".replace(",", ".")
    return f"{number:,.2f}".replace(",", "_").replace(".", ",").replace("_", ".")


def _numeric_column_names(data_profile: dict[str, Any]) -> set[str]:
    return {
        str(column.get("name") or "").strip()
        for column in _as_list(data_profile.get("numericColumns"))
        if isinstance(column, dict) and str(column.get("name") or "").strip()
    }


def _known_dimension_names(data_profile: dict[str, Any]) -> set[str]:
    names = set()
    for group in _as_list(data_profile.get("topGroups")):
        if isinstance(group, dict) and group.get("groupBy"):
            names.add(str(group.get("groupBy")).strip())
    return names


def _parse_numeric_cell(value: Any) -> float | None:
    if isinstance(value, (int, float)):
        return float(value)
    text = str(value or "").strip()
    if not text:
        return None
    normalized = (
        text.replace(" ", "")
        .replace("đ", "")
        .replace("₫", "")
        .replace("%", "")
    )
    if "," in normalized and "." in normalized:
        normalized = normalized.replace(".", "").replace(",", ".")
    elif "," in normalized:
        normalized = normalized.replace(",", ".")
    try:
        return float(normalized)
    except ValueError:
        return None


def _compute_numeric_summary(rows: list[dict[str, Any]], column: str) -> dict[str, Any] | None:
    values = [
        number
        for number in (_parse_numeric_cell(row.get(column)) for row in rows)
        if number is not None
    ]
    if not values:
        return None
    total = sum(values)
    return {
        "type": "python_aggregate",
        "column": column,
        "count": len(values),
        "sum": total,
        "average": total / len(values),
        "min": min(values),
        "max": max(values),
    }


def _compute_group_aggregate(
    rows: list[dict[str, Any]],
    group_column: str,
    metric_column: str,
    limit: int,
) -> dict[str, Any] | None:
    if not group_column or not metric_column:
        return None
    totals: dict[str, float] = {}
    counts: dict[str, int] = {}
    for row in rows:
        group = str(row.get(group_column) or "Chưa xác định").strip() or "Chưa xác định"
        number = _parse_numeric_cell(row.get(metric_column))
        if number is None:
            continue
        totals[group] = totals.get(group, 0) + number
        counts[group] = counts.get(group, 0) + 1
    if not totals:
        return None
    top_groups = [
        {
            "group": group,
            "total": total,
            "count": counts.get(group, 0),
            "average": total / max(1, counts.get(group, 0)),
        }
        for group, total in sorted(totals.items(), key=lambda item: item[1], reverse=True)
    ][:limit]
    return {
        "type": "python_group_aggregate",
        "groupBy": group_column,
        "metric": metric_column,
        "topGroups": top_groups,
    }


def build_analysis_plan(data_profile: dict[str, Any]) -> dict[str, Any]:
    """Create a deterministic plan from the verified spreadsheet profile.

    Gemini may later interpret the result, but execution starts from a safe
    plan generated by the service instead of arbitrary model output.
    """

    operations: list[dict[str, Any]] = [{"type": "SUMMARY"}]

    numeric_columns = _as_list(data_profile.get("numericColumns"))
    top_groups = _as_list(data_profile.get("topGroups"))
    anomalies = _as_list(data_profile.get("anomalies"))
    correlations = _as_list(data_profile.get("correlations"))
    time_series = _as_list(data_profile.get("timeSeries"))
    predictions = _as_list(data_profile.get("predictions"))

    if top_groups:
        first_group = top_groups[0] if isinstance(top_groups[0], dict) else {}
        operations.append(
            {
                "type": "GROUP",
                "column": first_group.get("groupBy") or "",
            }
        )
        if first_group.get("metric"):
            operations.append(
                {
                    "type": "AGGREGATE",
                    "column": first_group.get("metric"),
                    "function": "SUM",
                }
            )
        operations.append(
            {
                "type": "SORT",
                "column": first_group.get("metric") or first_group.get("groupBy") or "",
                "direction": "DESC",
            }
        )
    elif numeric_columns:
        first_numeric = numeric_columns[0] if isinstance(numeric_columns[0], dict) else {}
        operations.append(
            {
                "type": "AGGREGATE",
                "column": first_numeric.get("name") or "",
                "function": "SUM",
            }
        )

    if anomalies:
        operations.append({"type": "OUTLIER"})

    if correlations:
        operations.append({"type": "CORRELATION"})

    if time_series:
        operations.append({"type": "TREND"})

    if predictions:
        operations.append({"type": "FORECAST"})

    return {
        "operations": operations,
        "limit": 5,
    }


def validate_analysis_plan(
    plan: dict[str, Any],
    data_profile: dict[str, Any],
) -> tuple[bool, list[str], dict[str, Any]]:
    errors: list[str] = []
    if not isinstance(plan, dict):
        return False, ["Analysis Plan không hợp lệ."], {"operations": [{"type": "SUMMARY"}], "limit": 5}

    operations = _as_list(plan.get("operations"))
    if not operations:
        errors.append("Analysis Plan không có operation.")

    numeric_columns = _numeric_column_names(data_profile)
    dimension_columns = _known_dimension_names(data_profile)
    sanitized_operations: list[dict[str, Any]] = []

    for operation in operations:
        if not isinstance(operation, dict):
            errors.append("Operation không đúng định dạng.")
            continue

        operation_type = str(operation.get("type") or "").upper().strip()
        if operation_type not in ALLOWED_OPERATIONS:
            errors.append(f"Operation không được phép: {operation_type}")
            continue

        sanitized: dict[str, Any] = {"type": operation_type}
        column = str(operation.get("column") or "").strip()

        if operation_type in {"AGGREGATE", "SORT"}:
            if column and column not in numeric_columns and column not in dimension_columns:
                errors.append(f"Cột không tồn tại trong profile: {column}")
            if operation_type == "AGGREGATE" and column and column not in numeric_columns:
                errors.append(f"AGGREGATE chỉ dùng với cột số: {column}")
            if column:
                sanitized["column"] = column

        if operation_type == "GROUP":
            if column and column not in dimension_columns:
                errors.append(f"GROUP dùng cột chưa có trong profile: {column}")
            if column:
                sanitized["column"] = column

        if operation_type == "FILTER":
            sanitized_conditions = []
            for condition in _as_list(operation.get("conditions")):
                if not isinstance(condition, dict):
                    errors.append("FILTER condition không đúng định dạng.")
                    continue
                condition_column = str(condition.get("column") or "").strip()
                operator = str(condition.get("operator") or "").strip()
                if condition_column not in numeric_columns and condition_column not in dimension_columns:
                    errors.append(f"FILTER dùng cột không tồn tại: {condition_column}")
                if operator not in ALLOWED_FILTER_OPERATORS:
                    errors.append(f"FILTER operator không được phép: {operator}")
                sanitized_conditions.append(
                    {
                        "column": condition_column,
                        "operator": operator,
                        "value": condition.get("value"),
                        "strategy": condition.get("strategy"),
                    }
                )
            sanitized["conditions"] = sanitized_conditions

        if operation_type == "AGGREGATE":
            function = str(operation.get("function") or "SUM").upper().strip()
            if function not in ALLOWED_AGGREGATES:
                errors.append(f"Hàm aggregate không được phép: {function}")
            sanitized["function"] = function

        if operation_type == "SORT":
            direction = str(operation.get("direction") or "DESC").upper().strip()
            sanitized["direction"] = "ASC" if direction == "ASC" else "DESC"

        sanitized_operations.append(sanitized)

    limit = plan.get("limit", 5)
    try:
        safe_limit = int(limit)
    except (TypeError, ValueError):
        safe_limit = 5
    safe_limit = max(SAFE_LIMIT_MIN, min(SAFE_LIMIT_MAX, safe_limit))

    sanitized_plan = {
        "operations": sanitized_operations or [{"type": "SUMMARY"}],
        "limit": safe_limit,
    }
    return len(errors) == 0, errors, sanitized_plan


def execute_analysis_plan(
    plan: dict[str, Any],
    data_profile: dict[str, Any],
    computed_insights: dict[str, Any],
) -> dict[str, Any]:
    """Execute the safe plan against verified profile-level data.

    The current Node layer already computes the spreadsheet statistics. This
    executor does not let Gemini calculate numbers; it selects and packages
    those verified values into a structured result.
    """

    operations = _as_list(plan.get("operations"))
    operation_types = {operation.get("type") for operation in operations if isinstance(operation, dict)}
    result_rows: list[dict[str, Any]] = []
    row_sample = [
        row
        for row in _as_list(data_profile.get("rowSample"))
        if isinstance(row, dict)
    ]
    limit = int(plan.get("limit") or 5)

    aggregate_column = ""
    group_column = ""
    for operation in operations:
        if not isinstance(operation, dict):
            continue
        if operation.get("type") == "AGGREGATE" and operation.get("column"):
            aggregate_column = str(operation.get("column"))
        if operation.get("type") == "GROUP" and operation.get("column"):
            group_column = str(operation.get("column"))

    if row_sample and aggregate_column:
        numeric_summary = _compute_numeric_summary(row_sample, aggregate_column)
        if numeric_summary:
            result_rows.append(numeric_summary)

    if row_sample and group_column and aggregate_column:
        group_summary = _compute_group_aggregate(
            row_sample,
            group_column,
            aggregate_column,
            limit,
        )
        if group_summary:
            result_rows.append(group_summary)

    for column in _as_list(data_profile.get("numericColumns")):
        if not isinstance(column, dict):
            continue
        result_rows.append(
            {
                "type": "numeric_summary",
                "column": column.get("name") or "",
                "sum": column.get("sum"),
                "average": column.get("average"),
                "min": column.get("min"),
                "max": column.get("max"),
            }
        )

    for group in _as_list(data_profile.get("topGroups")):
        if not isinstance(group, dict):
            continue
        result_rows.append(
            {
                "type": "group_top",
                "groupBy": group.get("groupBy") or "",
                "metric": group.get("metric") or "",
                "topGroups": _as_list(group.get("topGroups"))[:3],
            }
        )

    if "OUTLIER" in operation_types:
        for anomaly in _as_list(data_profile.get("anomalies")):
            if isinstance(anomaly, dict):
                result_rows.append({"type": "outlier", **anomaly})

    if "CORRELATION" in operation_types:
        for correlation in _as_list(data_profile.get("correlations")):
            if isinstance(correlation, dict):
                result_rows.append({"type": "correlation", **correlation})

    if "TREND" in operation_types:
        for trend in _as_list(data_profile.get("timeSeries")):
            if isinstance(trend, dict):
                result_rows.append({"type": "trend", **trend})

    if "FORECAST" in operation_types:
        for prediction in _as_list(data_profile.get("predictions")):
            if isinstance(prediction, dict):
                result_rows.append({"type": "forecast", **prediction})

    result_rows = result_rows[:limit]

    return {
        "analysisType": "SPREADSHEET_PROFILE",
        "query": "Phân tích tổng quan dữ liệu đã upload",
        "operationsExecuted": [
            _describe_operation(operation) for operation in operations if isinstance(operation, dict)
        ],
        "result": result_rows,
        "rowCount": len(result_rows),
        "sourceRowCount": data_profile.get("rowCount") or 0,
        "verified": True,
        "fallbackUsed": False,
        "computedInsights": computed_insights,
    }


def _describe_operation(operation: dict[str, Any]) -> str:
    operation_type = str(operation.get("type") or "").upper()
    if operation_type == "AGGREGATE":
        return f"{operation.get('function', 'SUM')} {operation.get('column', '')}".strip()
    if operation_type == "GROUP":
        return f"GROUP {operation.get('column', '')}".strip()
    if operation_type == "SORT":
        return f"SORT {operation.get('column', '')} {operation.get('direction', 'DESC')}".strip()
    return operation_type


def _fallback_agent_result(
    *,
    data_profile: dict[str, Any],
    computed_insights: dict[str, Any],
    execution_result: dict[str, Any] | None = None,
) -> dict[str, Any]:
    insights = _as_list(computed_insights.get("insights"))
    recommended_actions = _as_list(computed_insights.get("recommendedActions"))
    chart_suggestions = _as_list(computed_insights.get("chartSuggestions"))
    predictions = _as_list(computed_insights.get("predictions"))
    anomalies = _as_list(computed_insights.get("anomalies"))

    suggested_tasks = []

    if recommended_actions:
        suggested_tasks.append(
            {
                "title": "Rà soát dữ liệu quan trọng",
                "description": "Task nháp từ Data Analysis Agent để kiểm tra các insight, rủi ro và bất thường trong file.",
                "category": "Work",
                "type": "Task",
                "domain": "Data Analysis",
                "difficulty": "Trung bình",
                "necessity": "Cao" if anomalies else "Trung bình",
                "priority": "Cao" if anomalies else "Trung bình",
                "startDate": "",
                "deadline": "",
                "startTime": "",
                "endTime": "",
                "estimate": "45 phút",
                "reminder": "Không nhắc",
                "assignee": "Tôi",
                "status": "To do",
                "completed": False,
                "suggestedSteps": recommended_actions[:4],
            }
        )

    return {
        "summary": (
            f"Dữ liệu có {data_profile.get('sheetCount', 0)} sheet/bảng, "
            f"{data_profile.get('rowCount', 0)} dòng và "
            f"{data_profile.get('numericColumnCount', 0)} cột số có thể phân tích."
        ),
        "insights": insights,
        "anomalies": anomalies,
        "predictions": predictions,
        "chartSuggestions": chart_suggestions,
        "recommendedActions": recommended_actions,
        "suggestedTasks": suggested_tasks,
        "analysisSource": "data-analysis-agent-local",
        "dataAnalysis": execution_result or {},
    }


def normalize_agent_result(result: dict[str, Any], fallback: dict[str, Any]) -> dict[str, Any]:
    if not isinstance(result, dict):
        result = {}

    return {
        "summary": str(result.get("summary") or fallback.get("summary") or "").strip(),
        "insights": _as_list(result.get("insights")) or _as_list(fallback.get("insights")),
        "anomalies": _as_list(result.get("anomalies")) or _as_list(fallback.get("anomalies")),
        "predictions": _as_list(result.get("predictions")) or _as_list(fallback.get("predictions")),
        "chartSuggestions": _as_list(result.get("chartSuggestions")) or _as_list(fallback.get("chartSuggestions")),
        "recommendedActions": _as_list(result.get("recommendedActions")) or _as_list(fallback.get("recommendedActions")),
        "suggestedTasks": _as_list(result.get("suggestedTasks")) or _as_list(fallback.get("suggestedTasks")),
        "analysisSource": result.get("analysisSource") or "data-analysis-agent",
        "dataAnalysis": fallback.get("dataAnalysis") or {},
    }


def run_data_analysis_agent(
    *,
    data_insights: dict[str, Any] | None,
    file_name: str,
    document_text: str,
    gemini_model: Any | None = None,
) -> dict[str, Any] | None:
    if not data_insights:
        return None

    data_profile = build_data_profile(data_insights)
    computed_insights = build_computed_data_insights(data_profile)
    analysis_plan = build_analysis_plan(data_profile)
    is_valid, validation_errors, validated_plan = validate_analysis_plan(
        analysis_plan,
        data_profile,
    )

    if is_valid:
        execution_result = execute_analysis_plan(
            validated_plan,
            data_profile,
            computed_insights,
        )
    else:
        execution_result = {
            "analysisType": "FALLBACK_PROFILE",
            "query": "Phân tích tổng quan dữ liệu đã upload",
            "operationsExecuted": ["SUMMARY"],
            "result": [],
            "rowCount": 0,
            "sourceRowCount": data_profile.get("rowCount") or 0,
            "verified": False,
            "fallbackUsed": True,
            "validationErrors": validation_errors,
            "computedInsights": computed_insights,
        }

    data_analysis = {
        **execution_result,
        "analysisPlan": analysis_plan,
        "validatedPlan": validated_plan,
        "validationErrors": validation_errors,
        "dataProfile": data_profile,
    }

    fallback = _fallback_agent_result(
        data_profile=data_profile,
        computed_insights=computed_insights,
        execution_result=data_analysis,
    )

    if gemini_model is None:
        return {
            **fallback,
            "dataProfile": data_profile,
            "computedInsights": computed_insights,
            "dataAnalysis": data_analysis,
        }

    try:
        prompt = build_data_analysis_prompt(
            file_name=file_name,
            document_text=document_text,
            data_profile=data_profile,
            computed_insights={
                **computed_insights,
                "analysisPlan": validated_plan,
                "executionResult": execution_result,
            },
        )
        response = gemini_model.generate_content(prompt)
        parsed = json.loads(_clean_json_text(response.text))
        normalized = normalize_agent_result(parsed, fallback)
        return {
            **normalized,
            "dataProfile": data_profile,
            "computedInsights": computed_insights,
            "dataAnalysis": data_analysis,
        }
    except Exception as error:
        print("Data Analysis Agent fallback:", error)
        return {
            **fallback,
            "dataProfile": data_profile,
            "computedInsights": computed_insights,
            "dataAnalysis": data_analysis,
        }
